server:
  port: 8080

spring:
  profiles:
    active: dev
  main:
    allow-circular-references: true
  datasource:
    druid:
      driver-class-name: ${sky.datasource.driver-class-name}
      url: jdbc:mysql://${sky.datasource.host}:${sky.datasource.port}/${sky.datasource.database}?serverTimezone=Asia/Shanghai&useUnicode=true&characterEncoding=utf-8&zeroDateTimeBehavior=convertToNull&useSSL=false&allowPublicKeyRetrieval=true
      username: ${sky.datasource.username}
      password: ${sky.datasource.password}

mybatis-plus:
  # 1. 通用配置
  configuration:
    map-underscore-to-camel-case: true     # 开启驼峰映射 user_name → userName
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl # 打印 SQL（开发阶段常用）

  # 2. 全局配置
  global-config:
    banner: false                          # 关闭启动 banner
    db-config:
      id-type: auto                        # 主键策略：数据库自增
      logic-delete-field: deleted          # 逻辑删除字段
      logic-delete-value: 1                # 已删除值
      logic-not-delete-value: 0            # 未删除值

  # 3. Mapper XML 位置
  mapper-locations: classpath*:mapper/**/*.xml

  # 4. 别名包
  type-aliases-package: com.sky.entity


logging:
  level:
    com:
      sky:
        mapper: trace
        service: info
        controller: info

sky:
  jwt:
    # 设置jwt签名加密时使用的秘钥
    admin-secret-key: itcast
    # 设置jwt过期时间
    admin-ttl: 720000000
    # 设置前端传递过来的令牌名称
    admin-token-name: token

minio:
  endpoint: http://124.222.138.172:19000
  accessKey: minioadmin
  secretKey: minioadmin
  bucket: sky-take-out

